(load "../data/gesamt.lisp")
(load "libs/vendor/versionspace.lsp")
(load "libs/create_neg_pos.lisp")
(load "libs/aq.lisp")
 
(print "Start Training")
(setq JAZZ_K (do-AQ pexamples nexamples))
(print "End Training")
(print "JAZZ_K:")
(print JAZZ_K)
